export const GENRES = [
    { "name": "Action and Adventure", "value": "action_and_adventure" },
    { "name": "Biography and Memoir", "value": "biography_and_memoir" },
    { "name": "Classics", "value": "classics" },
    { "name": "Comic and Graphic Novel", "value": "comic_and_graphic_novel" },
    { "name": "Contemporary Fiction", "value": "contemporary_fiction" },
    { "name": "Drama", "value": "drama" },
    { "name": "Dystopian", "value": "dystopian" },
    { "name": "Fantasy", "value": "fantasy" },
    { "name": "Historical Fiction", "value": "historical_fiction" },
    { "name": "Horror", "value": "horror" },
    { "name": "Humor", "value": "humor" },
    { "name": "Literary Fiction", "value": "literary_fiction" },
    { "name": "Mystery and Crime", "value": "mystery_and_crime" },
    { "name": "Non-fiction", "value": "non_fiction" },
    { "name": "Paranormal", "value": "paranormal" },
    { "name": "Poetry", "value": "poetry" },
    { "name": "Political Fiction", "value": "political_fiction" },
    { "name": "Romance", "value": "romance" },
    { "name": "Science Fiction", "value": "science_fiction" },
    { "name": "Self-Help", "value": "self_help" },
    { "name": "Short Stories", "value": "short_stories" },
    { "name": "Suspense and Thriller", "value": "suspense_and_thriller" },
    { "name": "Travel Literature", "value": "travel_literature" },
    { "name": "Western", "value": "western" },
    { "name": "Young Adult", "value": "young_adult" },
    { "name": "Erotic", "value": "erotic" },
  ]
export const INTERESTS = [
    { "name": "Adventure", "value": "adventure" },
    { "name": "AI and Technology", "value": "ai_and_technology" },
    { "name": "Coming of Age", "value": "coming_of_age" },
    { "name": "Crime and Mystery", "value": "crime_and_mystery" },
    { "name": "Dystopia", "value": "dystopia" },
    { "name": "Epic Fantasy", "value": "epic_fantasy" },
    { "name": "Historical Fiction", "value": "historical_fiction" },
    { "name": "Horror and Supernatural", "value": "horror_and_supernatural" },
    { "name": "Humor and Satire", "value": "humor_and_satire" },
    { "name": "Inspirational", "value": "inspirational" },
    { "name": "Love and Relationships", "value": "love_and_relationships" },
    { "name": "Magic and Mythology", "value": "magic_and_mythology" },
    { "name": "Mental Health and Well-being", "value": "mental_health_and_well_being" },
    { "name": "Personal Growth", "value": "personal_growth" },
    { "name": "Philosophy and Ethics", "value": "philosophy_and_ethics" },
    { "name": "Politics and Society", "value": "politics_and_society" },
    { "name": "Psychological Thriller", "value": "psychological_thriller" },
    { "name": "Science and Exploration", "value": "science_and_exploration" },
    { "name": "Science Fiction", "value": "science_fiction" },
    { "name": "Self-Help and Productivity", "value": "self_help_and_productivity" },
    { "name": "Space Exploration", "value": "space_exploration" },
    { "name": "Sports and Competitions", "value": "sports_and_competitions" },
    { "name": "Travel and Adventure", "value": "travel_and_adventure" },
    { "name": "True Crime", "value": "true_crime" },
    { "name": "War and Military", "value": "war_and_military" },
    { "name": "Mindfulness", "value": "mindfulness" }
  ]
export const TONES = [
    { "name": "Positive", "value": "positive" },
    { "name": "Neutral", "value": "neutral" },
    { "name": "Negative", "value": "negative" },
    { "name": "Confident", "value": "confident" },
    { "name": "Assertive", "value": "assertive" },
    { "name": "Calm", "value": "calm" },
    { "name": "Relaxed", "value": "relaxed" },
    { "name": "Creative", "value": "creative" },
    { "name": "Empathetic", "value": "empathetic" },
    { "name": "Analytical", "value": "analytical" },
    { "name": "Logical", "value": "logical" },
    { "name": "Emotional", "value": "emotional" },
    { "name": "Intuitive", "value": "intuitive" },
    { "name": "Sensory", "value": "sensory" },
    { "name": "Visual", "value": "visual" },
    { "name": "Auditory", "value": "auditory" },
    { "name": "Kinesthetic", "value": "kinesthetic" },
    { "name": "Mixed", "value": "mixed" },
    { "name": "Authentic", "value": "authentic" },
    { "name": "Professional", "value": "professional" },
  ]
export const READING_PURPOSES = [
    { "name": "Learning", "value": "learning" },
    { "name": "Inspiration", "value": "inspiration" },
    { "name": "Relaxation", "value": "relaxation" },
  ]

